/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

import java.util.ArrayList;
import java.io.Serializable;

public class Library implements Serializable{
    private ArrayList<Transaction> transactions;
    private ArrayList<Person> people;
    private ArrayList<Shelf> shelves;

    public Library(){
        transactions = new ArrayList<>();
        people = new ArrayList<>();
        shelves = new ArrayList<>();
    }
    public Library(ArrayList<Transaction> transactions, ArrayList<Person> people){
        this.people = people;
        this.transactions = transactions;
    }


    /**
     * @param ID - id generated by the ID manager;
     * @param birthYear - birthyear;
     * @param name - name;
     * @param surname - surname;
     * @param contact - contact;
     * @param typeOfPerson - 'C' - Client
     *                     - 'E' - Employee
     *                     - '' - default case, will be created as a Person;
     * */
    public void addPerson(int ID, int birthYear, String name, String surname, Contact contact, char typeOfPerson){
        switch (typeOfPerson){
            case 'E':
                people.add(new Employee(ID, birthYear, name, surname, contact));
                break;
            case 'C':
                people.add(new Client(ID, birthYear, name, surname, contact));
                break;
            default: people.add(new Person(ID, birthYear, name, surname, contact));
        }

    }
    public void addTransaction(Transaction transaction){
        transactions.add(transaction);
    }


    public Item getItemByID(int ID){
        for (Shelf s : shelves){
            Item i = s.getItemByID(ID);
            if(i != null){
                return i;
            }
        }
        return null;
    }

    public Transaction getTransactionByID(int ID){
        for(Transaction t : transactions){
            if(t.getID() == ID){
                return t;
            }
        }
        return null;
    }

    public Person getPersonByID(int ID){
        for(Person p : people){
            if(p.getID() == ID){
                return p;
            }
        }
        return null;
    }
    
}
